# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/programmor/proto/transaction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&src/programmor/proto/transaction.proto\"\xc8\x01\n\x12TransactionMessage\x12\r\n\x05token\x18\x01 \x01(\x07\x12*\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x1a.TransactionMessage.Action\x12\x0f\n\x07shareId\x18\x03 \x01(\x07\x12\x12\n\ndataLength\x18\x04 \x01(\x07\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\"D\n\x06\x41\x63tion\x12\x06\n\x02NA\x10\x00\x12\n\n\x06\x43OMMON\x10\x01\x12\x0b\n\x07REQUEST\x10\x02\x12\x0b\n\x07PUBLISH\x10\x03\x12\x0c\n\x08RESPONSE\x10\x04\"\x83\x01\n\x07\x43ommon1\x12\n\n\x02id\x18\x01 \x01(\x07\x12\x12\n\nregistryId\x18\x02 \x01(\x07\x12\x14\n\x0cserialNumber\x18\x03 \x01(\x07\x12\x15\n\rsharesVersion\x18\x04 \x01(\x07\x12\x17\n\x0f\x66irmwareVersion\x18\x05 \x01(\x07\x12\x12\n\ndeviceName\x18\x06 \x01(\tb\x06proto3')



_TRANSACTIONMESSAGE = DESCRIPTOR.message_types_by_name['TransactionMessage']
_COMMON1 = DESCRIPTOR.message_types_by_name['Common1']
_TRANSACTIONMESSAGE_ACTION = _TRANSACTIONMESSAGE.enum_types_by_name['Action']
TransactionMessage = _reflection.GeneratedProtocolMessageType('TransactionMessage', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONMESSAGE,
  '__module__' : 'src.programmor.proto.transaction_pb2'
  # @@protoc_insertion_point(class_scope:TransactionMessage)
  })
_sym_db.RegisterMessage(TransactionMessage)

Common1 = _reflection.GeneratedProtocolMessageType('Common1', (_message.Message,), {
  'DESCRIPTOR' : _COMMON1,
  '__module__' : 'src.programmor.proto.transaction_pb2'
  # @@protoc_insertion_point(class_scope:Common1)
  })
_sym_db.RegisterMessage(Common1)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSACTIONMESSAGE._serialized_start=43
  _TRANSACTIONMESSAGE._serialized_end=243
  _TRANSACTIONMESSAGE_ACTION._serialized_start=175
  _TRANSACTIONMESSAGE_ACTION._serialized_end=243
  _COMMON1._serialized_start=246
  _COMMON1._serialized_end=377
# @@protoc_insertion_point(module_scope)
