# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: programmor_adapters/test_adapter/proto/test.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'programmor_adapters/test_adapter/proto/test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1programmor_adapters/test_adapter/proto/test.proto\"G\n\x06Share1\x12\x16\n\x0estartingNumber\x18\x01 \x01(\x0f\x12\x14\n\x0c\x65ndingNumber\x18\x02 \x01(\x0f\x12\x0f\n\x07\x63ounter\x18\x03 \x01(\x0f\"w\n\x06Share2\x12\x1b\n\x13\x66requencyInputPinId\x18\x01 \x01(\x0f\x12\x1a\n\x12\x64igitalOutputPinId\x18\x02 \x01(\x0f\x12\x19\n\x11\x61nalogInputAPinId\x18\x03 \x01(\x0f\x12\x19\n\x11\x61nalogInputBPinId\x18\x04 \x01(\x0f\" \n\x06Share3\x12\x16\n\x0eloopsPerSecond\x18\x01 \x01(\x0f\"\x1d\n\x06Share4\x12\x13\n\x0bwelcomeText\x18\x01 \x01(\t\"\x82\x01\n\x06Share5\x12\x13\n\x0b\x66loatNumber\x18\x01 \x01(\x02\x12\x14\n\x0c\x64oubleNumber\x18\x02 \x01(\x01\x12\x11\n\tipAddress\x18\x03 \x01(\t\x12\x12\n\nportNumber\x18\x04 \x01(\x0f\x12\x10\n\x08\x64\x61teTime\x18\x05 \x01(\t\x12\x14\n\x0c\x62ooleanValue\x18\x06 \x01(\x08\"\x1e\n\x06Share6\x12\x14\n\x0c\x64\x61yOfTheWeek\x18\x01 \x01(\x0f\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'programmor_adapters.test_adapter.proto.test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHARE1']._serialized_start=53
  _globals['_SHARE1']._serialized_end=124
  _globals['_SHARE2']._serialized_start=126
  _globals['_SHARE2']._serialized_end=245
  _globals['_SHARE3']._serialized_start=247
  _globals['_SHARE3']._serialized_end=279
  _globals['_SHARE4']._serialized_start=281
  _globals['_SHARE4']._serialized_end=310
  _globals['_SHARE5']._serialized_start=313
  _globals['_SHARE5']._serialized_end=443
  _globals['_SHARE6']._serialized_start=445
  _globals['_SHARE6']._serialized_end=475
# @@protoc_insertion_point(module_scope)
